[package]
name = "context-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pin-project-lite = "0.2.9"
typemap_rev = "0.3.0"

[dev-dependencies]
futures-util = "0.3.25"
